import { ChiefEngine } from "@/lib/ai/chief-engine";
import ReactMarkdown from "react-markdown";

export default async function DailyBriefingPage() {
  // Generates on page load. Caches automatically inside the ChiefEngine class.
  const briefingText = await ChiefEngine.generateDailyBriefing();

  return (
    <div className="p-8 max-w-4xl mx-auto space-y-8 pb-24">
      <div className="border-b border-border pb-6">
        <h1 className="text-3xl font-bold tracking-tight mb-2">Daily Briefing</h1>
        <p className="text-muted-foreground text-sm">Automatically generated by your Chief of Staff.</p>
      </div>

      <div className="bg-card border border-border shadow-sm rounded-xl p-8 prose prose-slate max-w-none">
        <ReactMarkdown>{briefingText}</ReactMarkdown>
      </div>
    </div>
  );
}
